// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXF10M25NBb7AWZPNyKZ6dBOoGXbz-HNQ',
    appId: '1:659717741243:web:aab77b1a78d64e9c0d679e',
    messagingSenderId: '659717741243',
    projectId: 'don-t-you-dare-forget-aefde',
    authDomain: 'don-t-you-dare-forget-aefde.firebaseapp.com',
    storageBucket: 'don-t-you-dare-forget-aefde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFOsRTHxgHY5BkWdF9aiGiqw83d0gGMgs',
    appId: '1:659717741243:android:697fbabe46fceacd0d679e',
    messagingSenderId: '659717741243',
    projectId: 'don-t-you-dare-forget-aefde',
    storageBucket: 'don-t-you-dare-forget-aefde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW1pRYyMaH9HU_xNE8Zw1bR5eyc6X-ArE',
    appId: '1:659717741243:ios:9d650bad9596c5bf0d679e',
    messagingSenderId: '659717741243',
    projectId: 'don-t-you-dare-forget-aefde',
    storageBucket: 'don-t-you-dare-forget-aefde.appspot.com',
    iosBundleId: 'com.example.mobileChecklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW1pRYyMaH9HU_xNE8Zw1bR5eyc6X-ArE',
    appId: '1:659717741243:ios:ebb0d87ce30eb1810d679e',
    messagingSenderId: '659717741243',
    projectId: 'don-t-you-dare-forget-aefde',
    storageBucket: 'don-t-you-dare-forget-aefde.appspot.com',
    iosBundleId: 'com.example.mobileChecklist.RunnerTests',
  );
}
